# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [ build ]
    typedb-driver: [ build, release ]

build:
  quality:
    filter:
      owner: typedb
      branch: master
    dependency-analysis:
      image: typedb-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//factory/analysis:dependency-analysis
  correctness:
    build:
      image: typedb-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel build //...
        # bazel run @typedb_dependencies//tool/checkstyle:test-coverage # TODO: reinstate when .bazelignore is empty or checkstyle respects it
        bazel test $(bazel query 'kind(checkstyle_test, //...)') --test_output=errors
    build-dependency:
      image: typedb-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
    test-unit:
      image: typedb-ubuntu-22.04
      dependencies:
        - build
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel test $(bazel query 'kind(kt_jvm_test, //...) except kind(kt_jvm_test, //test/...)') --test_output=errors
#    test-integration:
#      machine: 8-core-32-gb
#      image: typedb-ubuntu-22.04
#      dependencies:
#        - build
#      command: |
#        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
#        bazel build //test/integration/...
#        bazel test $(bazel query '//test/integration/... except kind(checkstyle_test, //test/integration/...)') --jobs=1 --spawn_strategy=local --test_output=errors

release:
  filter:
    owner: typedb
    branch: [master, development]
  validation:
    validate-release-notes:
      image: typedb-ubuntu-22.04
      command: |
        export NOTES_VALIDATE_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @typedb_dependencies//tool/release/notes:validate --test_output=streamed -- $FACTORY_OWNER $FACTORY_REPO ./RELEASE_NOTES_LATEST.md
  deployment:
    trigger-release-circleci:
      image: typedb-ubuntu-22.04
      command: |
        git checkout -b release
        git push -f origin release
        echo "Successfully pushed branch 'release', which triggers a release workflow in CircleCI. The progress of the release can be tracked here: https://app.circleci.com/pipelines/github/typedb/typedb-studio"
